events {}

http {
    server {
        listen 80;
	return 301 https://$host$request_uri;

        
    }

    server {
        listen 443 ssl;

        ssl_certificate     /cert.crt;
        ssl_certificate_key /cert.key;

        location / {
            proxy_pass http://openmaxio:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
