events {}

http {
    server {
        listen 80;
	
	    client_max_body_size 100000M; # Raise the max body size to allow larger files to be uploaded

        location / {
            proxy_pass http://openmaxio:9090;
	        proxy_http_version 1.1;
	        proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}